### PR TITLE
feat(type): update type package

### PR DESCRIPTION
**Pull request by joshblack**
Update `@carbon/type` with the values defined in https://github.com/carbon-design-system/issue-tracking/issues/27#issuecomment-422920858 for the product theme.

#### Testing & Review

Preview URLs

- [Typography example](https://joshblack.github.io/carbon-elements/type/examples/basic/index.html)

### CODE REVIEW

**Comment by joshblack** [comment]
cc @jeanservaas @aagonzales to confirm styles! The URL provided is just a dev playground so it has minimal, if any, styling outside of typography.

For verification, we have a couple of values that need to be checked, namely:

- Type scale itself
- Type styles (through the tokens)

**Comment by joshblack** [comment]
@asudoh yupp! Agreed 👍

**Comment by jeanservaas** [comment]
Quick question @joshblack -- type scale looks good but I don't see the Plex Serif for quotes in the Typography example anywhere (the quotation--01) Is this just because it oocupies the same size in the type scale as a Sans header? I noticed it because Plex Mono is represented in the example.

**Comment by joshblack** [comment]
@jeanservaas since those will be in editorial I ended up not placing them in the default theme here 👍 Let me know if that's not the case!

**Comment by aagonzales** [comment]
Yeah quotations are not in the product theme.

**Comment by joshblack** [comment]
@aagonzales could we update the table in https://github.com/carbon-design-system/issue-tracking/issues/27#issuecomment-422920858 with that info? Was going off of that 👍

**Comment by jeanservaas** [comment]
Hey @joshblack we're going to have to verify what the source of truth is for the values... Chiu's 0905_typescale file might be outdated because I'm seeing some different values around heading-05 and heading-06 (used to be ibm-type-e and ibm-type-f) on the new design language site. Ruh-roh. Stay tuned and I'll resolve this with chiu and erica tomorrow and get you a new table.

**Comment by joshblack** [comment]
Sounds good! Thanks @jeanservaas and @aagonzales

**Comment by jeanservaas** [comment]
ps @joshblack looks like margin bottom values are surfacing on the language site... I know Wonil and Chiu have been working on that stuff, so we should be able to cross apply to product. I'll look into that after I knock out a component or too.

**Comment by jeanservaas** [comment]
OK @joshblack -- these are the updated sizes in Product... the ONLY changes are to our Heading 05 and Heading 06 -- there are some scale changes at breakpoints and we don't use any Light weights in Product Headings so I fixed that.

## Fixed sizing
| Token | Use | Editorial | Product |
| :---     | :---      | :---    | :---     |
| code-01 | code | Step: 1<br> Font: PlexMono<br> Weight: 400/Regular<br> Size: 12px(0.75rem)<br> Line-height: 16px(1.333)<br>letter-spacing: 0.01rem | Step: 1<br> Font: PlexMono<br> Weight: 400/Regular<br> Size: 12px(0.75rem)<br> Line-height: 16px(1.333)<br>letter-spacing: 0.01rem | Step: 1<br> Font: PlexMono<br> Weight: 400/Regular<br> Size: 12px(0.75rem)<br> Line-height: 16px(1.333)<br>letter-spacing: 0.01rem |
| code-02 | code | Step: 2<br> Font: PlexMono<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 20px(1.429)<br>letter-spacing: 0.01rem | Step: 2<br> Font: PlexMono<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 20px(1.429)<br>letter-spacing: 0.01rem |
| body-01 | small copy | Step: 1<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 12px(0.75rem)<br> Line-height: 16px(1.333)<br>letter-spacing: 0.02rem | Step: 1<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 12px(0.75rem)<br> Line-height: 16px(1.333)<br>letter-spacing: 0.02rem |
| body-02 | body copy | Step: 2<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 20px(1.429)<br>letter-spacing: 0.01rem | Step: 2<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 20px(1.429)<br>letter-spacing: 0.01rem |
| body-03 | body copy | Step: 3<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 16px(1rem)<br> Line-height: 24px(1.5)<br>letter-spacing: 0rem | Step: 3<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 16px(1rem)<br> Line-height: 24px(1.5)<br>letter-spacing: 0rem |
| heading-01 | heading | Step: 2<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 18px(1.286)<br>letter-spacing: 0.01rem | Step: 2<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 14px(0.875rem)<br> Line-height: 18px(1.286)<br>letter-spacing: 0.01rem |
| heading-02 | heading | Step: 3<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 16px(1rem)<br> Line-height: 22px(1.375)<br>letter-spacing: 0rem | Step: 3<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 16px(1rem)<br> Line-height: 22px(1.375)<br>letter-spacing: 0rem |
| heading-03 | heading | Step: 3<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 16px(1rem)<br> Line-height: 22px(1.375)<br>letter-spacing: 0rem | Step: 3<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 16px(1rem)<br> Line-height: 22px(1.375)<br>letter-spacing: 0rem |



## Fluid sizing
| Token | Use | Editorial @sm | Editorial @med | Editorial @lg | Editorial @xlg | Editorial @max | Product @sm | Product @med | Product @lg | Product @xlg | Product @max |
| :---     | :---      | :---    | :---     | :---     | :---      | :---    | :---     | :---     | :---      | :---    | :---     |
| heading-04 | heading | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 5<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 20px(1.5rem)<br> Line-height: 26px(1.3)<br>letter-spacing: 0rem | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | 
| heading-05 | heading | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | Step: 7<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 28px(1.75rem)<br> Line-height: 36px(2.25)<br>letter-spacing: 0rem | Step: 8<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 9<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 36px(2.25rem)<br> Line-height: 44px(2.75)<br>letter-spacing: 0rem | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | Step: 6<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 24px(1.5rem)<br> Line-height: 30px(1.875)<br>letter-spacing: 0rem | Step: 7<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 28px(1.75rem)<br> Line-height: 36px(2.25)<br>letter-spacing: 0rem | Step: 8<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 32px(2.25rem)<br> Line-height: 40px(2.75)<br>letter-spacing: 0rem | Step: 9<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 36px(2rem)<br> Line-height: 44px(2.5)<br>letter-spacing: 0rem |
| heading-06 | heading | Step: 8<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 8<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 9<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 36px(2.25rem)<br> Line-height: 44px(2.75)<br>letter-spacing: 0rem | Step: 10<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 11<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 48px(3rem)<br> Line-height: 56px(3.5)<br>letter-spacing: 0rem | Step: 7<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 28px(1.75rem)<br> Line-height: 36px(2.25)<br>letter-spacing: 0rem | Step: 8<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 9<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 36px(2.25rem)<br> Line-height: 44px(2.75)<br>letter-spacing: 0rem | Step: 10<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 11<br> Font: PlexSans<br> Weight: 400/Regular<br> Size: 48px(3rem)<br> Line-height: 56px(3.5)<br>letter-spacing: 0rem |
| quotation-01 | quote | Step: 8<br> Font: PlexSerif<br> Weight: 300/Light<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 8<br> Font: PlexSerif<br> Weight: 300/Light<br> Size: 32px(2rem)<br> Line-height: 40px(2.5)<br>letter-spacing: 0rem | Step: 9<br> Font: PlexSerif<br> Weight: 300/Light<br> Size: 36px(2.25rem)<br> Line-height: 44px(2.75)<br>letter-spacing: 0rem | Step: 10<br> Font: PlexSerif<br> Weight: 300/Light<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 11<br> Font: PlexSerif<br> Weight: 300/Light<br> Size: 48px(3rem)<br> Line-height: 56px(3.5)<br>letter-spacing: 0rem | -- | -- | -- | -- | -- |
| display-01 | small display | Step: 10<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 10<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 12<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 54px(3.375rem)<br> Line-height: 64px(4)<br>letter-spacing: 0rem | Step: 13<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 60px(3.75rem)<br> Line-height: 70px(4.375)<br>letter-spacing: 0rem | Step: 15<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 76px(4.75rem)<br> Line-height: 86px(5.375)<br>letter-spacing: 0rem |  -- | -- | -- | -- | -- |
| display-02 | small display | Step: 10<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 10<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 12<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 54px(3.375rem)<br> Line-height: 64px(4)<br>letter-spacing: 0rem | Step: 13<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 60px(3.75rem)<br> Line-height: 70px(4.375)<br>letter-spacing: 0rem | Step: 15<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 76px(4.75rem)<br> Line-height: 86px(5.375)<br>letter-spacing: 0rem |  -- | -- | -- | -- | -- |
| display-03 | display | Step: 10<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 14<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 68px(4.25rem)<br> Line-height: 78px(4.875)<br>letter-spacing: 0rem | Step: 17<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 92px(5.75rem)<br> Line-height: 102px(6.375)<br>letter-spacing: -0.1rem | Step: 20<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 122px(7.625rem)<br> Line-height: 130px(8.125)<br>letter-spacing: -0.1rem | Step: 23<br> Font: PlexSans<br> Weight: 300/Light<br> Size: 156px(9.75rem)<br> Line-height: 164px(10.25)<br>letter-spacing: -0.2rem |  -- | -- | -- | -- | -- |
| display-04 | display | Step: 10<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 42px(2.625rem)<br> Line-height: 50px(3.125)<br>letter-spacing: 0rem | Step: 14<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 68px(4.25rem)<br> Line-height: 78px(4.875)<br>letter-spacing: 0rem | Step: 17<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 92px(5.75rem)<br> Line-height: 102px(6.375)<br>letter-spacing: -0.1rem | Step: 20<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 122px(7.625rem)<br> Line-height: 130px(8.125)<br>letter-spacing: -0.1rem | Step: 23<br> Font: PlexSans<br> Weight: 600/SemiBold<br> Size: 156px(9.75rem)<br> Line-height: 164px(10.25)<br>letter-spacing: -0.2rem |  -- | -- | -- | -- | -- |

**Comment by jeanservaas** [comment]
ps @joshblack looks like margin bottom values are surfacing on the language site... I know Wonil and Chiu have been working on that stuff, so we should be able to cross apply to product. I'll look into that after I knock out a component or too.

**Pull request merged**
