### PR TITLE
feat(layout): add layout package

### PR DESCRIPTION
**Pull request by joshblack**
Adds in an initial layout package. This will hold the utility helpers that we need for managing:

- Converting units from `px` to `rem` or `em`
- Mini unit value and utility function `mini-units` for getting a value for a number of units
- Spacing scale, similar to what exists in Carbon current but is based off of the mini-unit and is a scale instead of t-shirt sizes
- Breakpoints, also includes a `breakpoint` mixin for including content at various breakpoints. The smallest breakpoint does not have a media query and is instead the default value.
- Key heights, based on breakpoints. Useful for picking heights of things based off of current column height

In the future, we might want to add layers in this package.

#### Changelog

**New**

- `packages/layout` is now included with helpers above

**Changed**

**Removed**

#### Testing & Review

Preview URLs:

- [Basic example](https://joshblack.github.io/carbon-elements/layout/examples/basic/index.html)

### CODE REVIEW

**Comment by joshblack** [comment]
Some specific feedback I'm curious about from development:

- How do you feel about a `layout` package in the context of the Carbon Design System? Do the helpers in this package feel like they belong? Does this package seem useful?
- How do you feel about `mini-units` as the function for getting mini-unit values?
- How do you fee about a spacing scale instead of t-shirt sizes?

**Comment by joshblack** [comment]
For design, just want to confirm:

- [ ] Spacing scale looks as expected, including values: 0, 2px, 4px, 8px, 12px, 16px, 24px, 32px, 48px, 64px, 80px, 96px
- [ ] Key height blocks at the bottom match specs with respect to breakpoints

**Comment by alisonjoseph** [comment]
Thanks for putting this together! 🎉 

**How do you feel about a layout package in the context of the Carbon Design System? Do the helpers in this package feel like they belong? Does this package seem useful?**
What was the reasoning for pulling alll of this out of the main library? Do we see anyone using this without using the rest of Cabon Components? My only concern is its one more repo/package to maintain and adds another layer of complexity. also not 100% sure what everything like `key-height` etc is being used for? Maybe a walkthrough explanation would be helpful 🙏 

**How do you feel about mini-units as the function for getting mini-unit values?**
_I honestly don't love mini units in general (maybe I don't understand why we have them vs pixels), however, if that's what we are using now in all the designs then it makes sense to follow along in code._ 

**How do you fee about a spacing scale instead of t-shirt sizes?**
_I prefer T-shirt sizes personally, I think they are easier to understand and remember when writing code. However, they also limit how many options you can have in the scale. I know we had a bunch of discussion around this when we created spacing tokens and landed on t-shirt sizes for a reason.  _

**Comment by asudoh** [comment]
As @alisonjoseph alluded, more explanation wrt the addition here would be great. Given this PR seems to do fairly well on technical explanation (in API doc, etc.), I see that usage documentation (for consumers) will be a great help. Thanks!

**Comment by joshblack** [comment]
@asudoh sounds good, I can go more into details 👍 

As a pre-cursor, the idea behind the elements is that they are the packages to be distributed for building on top of the IBM Design Language. As a result, the elements of the design language (type, color, layout, icons, etc) are exposed through these packages in JavaScript and Sass formats. This will enable teams using Sass to include the work in their projects, in addition to exposing JavaScript so people can programmatically target their environment.

Building off of that, for layout we would expect the following responsibilities:

- Distributes the breakpoints that will apply to projects
- Distributes utility methods for reading and using column widths, this is relevant for things like key heights
- Distribute responsive key heights, which are used for deciding height value of fixed components of a page
- Distribute our spacing scale, used for component work
- Distribute a utility for expressing a value in terms of mini units. These values are used to drive almost every other value in the system

**Comment by joshblack** [comment]
For usage, I would anticipate folks to use our spacing constants and breakpoints as-is. Will provide better usage docs when we know what the patterns will be (they are still being defined). For mini units and key heights, I would look to our main slack channel where I'm also curious about how they will be used 👍

**Comment by SimonFinney** [comment]
@joshblack This is looking really clean so far, and I'm excited for us to try it out and introduce it into our projects - A couple of thoughts I had -

- Will these spacing / unit values be generated from JavaScript? If so, would it be possible to expose the JSON / definition files for these?
- Will there be one-to-one migration guides for migrating from the current IBM packages and Carbon v9? Specifically, grid functions (`get-fixed-size`) and spacing variables (`$spacing-*`) we currently use

**Comment by joshblack** [comment]
> Will these spacing / unit values be generated from JavaScript? If so, would it be possible to expose the JSON / definition files for these?

Yupp! 100% 😄 

> Will there be one-to-one migration guides for migrating from the current IBM packages and Carbon v9? Specifically, grid functions (get-fixed-size) and spacing variables ($spacing-*) we currently use

Yes, for sure. We will start writing them after the code is a little more stable 👍

**Comment by joshblack** [comment]
Thanks all for the comments!

**Pull request merged**
