### PR TITLE
feat(type): conditional CSS class definition

### PR DESCRIPTION
**Pull request by asudoh**
For `bx--type-*` and `html`/`body` styles.

Refs #143.

#### Changelog

**New**

- `$type--css-classes` and `$type--reset` Sass variable to conditionally exclude those CSS classes.

**Changed**

- Wrapped those CSS classes mentioned above in a mix-in.

### CODE REVIEW

**Comment by joshblack** [comment]
@asudoh this file is purposefully not included in the default entrypoint so that folks have to import it directly to use. Don't know if we need this guard due to this.

**Comment by asudoh** [comment]
@joshblack I see, the motivation is for including the file only when `carbon-components` is compiled in `v10` mode.

**Comment by joshblack** [comment]
@asudoh I don't think we want those classes included in carbon. They're only being generated for the digital use-case 👍 For carbon, we'd want to use the mixin, I think.

**Comment by asudoh** [comment]
@joshblack Got it - Thank you for clarifying! Removed the change to `_classes.scss`.

**Pull request merged**
