### PR TITLE
Feat/color states

### LINKED ISSUE #8: Include CSS variables for the different interaction states for color
From a suggestion from @seejamescode, it'd be great if we could include the interaction states for color as part of our output in SCSS, CSS, and JS variables for folks to use 👍

### PR DESCRIPTION
**Pull request by seejamescode**
Closes #8 

Adds different states of color and CSS Variables. CSS Variables not in the SCSS. I probably got a few of the new hex values wrong, but worth it to start somewhere.

#### Changelog

**New**

- Hover, selected, and active colors
- CSS file with CSS variables

### CODE REVIEW

**Comment by joshblack** [comment]
Hey @seejamescode! 👋 Thanks for making the PR 😄 Unfortunately, we need to wait for #12 to be resolved first since the strategy around interaction colors might change.

**Comment by seejamescode** [comment]
I don’t understand how that is a blocker today. The README already clarifies that this repo is experimental and anything could change. Based on my current project as a sponsor user, this is what I need today.

**Comment by joshblack** [comment]
@seejamescode this might be my fault for not properly communicating the intent of this project, but the goal of elements here is to support the Carbon X release for Dec. 10th and to provide packages for the updated IDL assets at that point. For work that is meant for teams using the internal monorepo, I would suggest pointing efforts towards that project.

This project has a high chance of divergence from that effort because of updates that are still happening to the elements and how we use them, similar to what you see in #12 and in #10, #13. Let me know and I can also share the internal mirror of those issues which have the full discussions in some cases.

**Comment by seejamescode** [comment]
I have no incentive to submit to an internal repo that will be replaced by this one. I also don’t understand how there could be any confusion that these variables are needed. If anything, you definitely need the hover variables in your experimental components today.

**Pull request closed without merging**
