### PR TITLE
Perf/subgrid improvement

### PR DESCRIPTION
**Pull request by seejamescode**
Using CSS Variables, we can decrease the file size (unminified and not compressed) from 150kb to 21kb. 🎉

### CODE REVIEW

**Comment by asudoh** [comment]
The description sounds great @seejamescode! Given CSS custom properties (variable) spec is not supported by IE11 - Are we doing some build-time resolution of those, or does the grid package here drop support for IE11?

**Comment by seejamescode** [comment]
Yeah, it hit me right after I submitted this PR. My brain is stuck right now.

**Comment by seejamescode** [comment]
Maybe we can come up with a graceful degradation for IE 11 and say subgrid is not supported for that browser.

**Comment by asudoh** [comment]
@seejamescode Thank you for mulling it over! I think “IE11 not supported” statement makes sense as long as the sub-grid feature is opt-in.

**Comment by seejamescode** [comment]
Do you think sub-grid needs to be opt-in? I don’t think the subgrid code would break IE 11. It just wouldn’t do anything.

**Comment by joshblack** [comment]
@seejamescode I see our "bundling" strategy as:

- Default entrypoint with all of the things
- Each "feature" split so that folks can pick-and-choose the features/functionality that they want

So by default it'd be included, but we should make sure that we can separate it out for that latter use-case.

**Comment by seejamescode** [comment]
That sounds great. Wish I had done it for CSS Gridish and would love to see it in the next major version.

**Pull request merged**
