### PR TITLE
fix: remove auto margin from grid

### PR DESCRIPTION
**Pull request by alisonjoseph**
Removes auto margin from grid, we shouldn't assume a user wants their grid centered.

### CODE REVIEW

**Comment by joshblack** [comment]
@alisonjoseph the decision for this was just based off of common grid systems (mostly bootstrap). Are there solid examples of popular grids not implementing this by default that we could point to in docs for this change?

**Comment by alisonjoseph** [comment]
Unsure, but is doing something just because bootstrap does reason enough to do it? 🤔 Its easy enough to add `margin: 0` if needed, or for someone to add `margin: 0 auto;` so I'm ok if you don't think it makes sense to make this change.

**Comment by alisonjoseph** [comment]
Makes sense, would it be worth adding a helper class to remove the auto margin or just let the user zero it out themselves?

**Comment by joshblack** [comment]
@alisonjoseph I'm up for any number of utility classes at this point, especially given some of the other requirements for grid. Have a recommendation? Down for anything

**Pull request closed without merging**
