### PR TITLE
fix: update layout tokens to match IDL

### LINKED ISSUE #469: layout: Layout tokens should reflect IDL recommendation for content spacing
Screen Shot 2019-04-03 at 1 46 50 PM

| token    | current(mu) | IDL(mu) |
| -------- | -------- | -------- |
| layout01 | 2        | 1        |
| layout02 | 3        | 2        |
| layout03 | 4        | 3        |
| layout04 | 6        | 4        |
| layout05 | 8        | 6        |
| layout06 | 12       | 8        |
| layout07 | 20       | 10       |
| layout08 |          | 12       |
| layout09 |          | 15       |

### PR DESCRIPTION
**Pull request by vpicone**
Closes #469

#### Changelog

**Changed**

- layout tokens

Screen Shot 2019-04-03 at 1 46 50 PM

| token    | current(mu) | IDL(mu) |
| -------- | -------- | -------- |
| layout01 | 2        | 1        |
| layout02 | 3        | 2        |
| layout03 | 4        | 3        |
| layout04 | 6        | 4        |
| layout05 | 8        | 6        |
| layout06 | 12       | 8        |
| layout07 | 20       | 10       |
| layout08 |          | 12       |
| layout09 |          | 15       |

### CODE REVIEW

**Comment by joshblack** [comment]
@vpicone should we update these in `scss` as well?

**Comment by vpicone** [comment]
We had a solid convo about this, and in the end we decided that having two disparate but overlapping spacing and layout scales without a clear definition of when each would be used isn't worth the overhead.

The layout scale could be combined to include the spacing scale by adding a 1/2mu value at the bottom end of the scale. I'd have to dig a bit to see if this would cause issues with components.

**Comment by vpicone** [comment]
The layout tokens are used in a couple places in carbon-components, so when we update the vendor tokens we'll need to also correct that.

**Comment by joshblack** [comment]
Yeah! Sounds good @vpicone. We should add some docs on the process either in `carbon-components` or `carbon-elements` too 👍

**Comment by vpicone** [comment]
Rather than change the layout tokens, I've just consolidated the missing layout tokens into the spacing scale.

In this way, we can switch to using the combined spacing scale rather than maintaining to conflicting/disparate scales. This approach also prevents breaking changes downstream. 

Eventually the layout tokens can be deprecated.

**Pull request merged**
