### PR TITLE
feat(type): add new token set

### LINKED ISSUE #104: New type tokens
**Is your feature request related to a problem? Please describe.**
The type tokens have been redone

**Describe the solution you'd like**
An update to the component, editorial layout and product layout tokens detailed out here: https://ibm.box.com/s/igvyfkpawrp0l0hm0mbyg1sdifeplpir

**Describe alternatives you've considered**
All the variations in the past

**Additional context**
Make in conjunction with Anna, Jeannie and Wonil. Should be completed before the v10 release

### PR DESCRIPTION
**Pull request by joshblack**
Closes #104 

Adds new token set from #104.

#### Changelog

**New**

**Changed**

- `@carbon/type`
  - Add new token set from #104 
  - Remove `font-face` entrypoint so consumers have to choose which fonts to load in
  - Add support for fluid type

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @eraymond25

**Comment by mjabbink** [comment]
Awesome.

**Comment by eraymond25** [comment]
Looks like the editorial tokens are not fluid, is there a reason they are just jumping from size to size rather than gradual, fluid resizing

**Comment by joshblack** [comment]
> Looks like the editorial tokens are not fluid, is there a reason they are just jumping from size to size rather than gradual, fluid resizing

They're implemented using the breakpoints which is what causes them to bump instead of grow. We can only do the grow at each change if we do font-sizes based on viewport units, just didn't know this was the requirement 👍 

> I'm also wondering if it makes sense to bring the scale all the way up to step 23 since the editorial tokens go up to 23

In code I had to update the scale to accommodate, just didn't update the demo preview. So it's there! 👍

**Comment by eraymond25** [comment]
Yes, sorry if that wasn't clear. the "Editorial Layout Tokens Fluid" section of the Box note should be a fluid growth rather than a jump. Thanks!

**Comment by eraymond25** [comment]
cc: @photodow

**Comment by joshblack** [comment]
Updating now @eraymond25!

**Comment by joshblack** [comment]
Latest link to verify: https://deploy-preview-117--carbon-elements.netlify.com/type/examples/basic/

cc @eraymond25 @aagonzales

**Comment by joshblack** [comment]
Good catch @aagonzales! Let me figure out what's going on

**Comment by wonilsuhibm** [comment]
Looks great. Do these tokens implement line height as well or is that applied elsewhere?

**Comment by mjabbink** [comment]
Very good catch @aagonzales! 
You guys should check-in with Cameron Calder on font smoothing. They have done a ton of research and recommend using it which improves the rendering and legibility of the type and they have found no evidence to not use it. All browsers support and if not it defaults to without. so not issues. They have the finding they can share but it’s worth investigating.

**Comment by wonilsuhibm** [comment]
Regarding font smoothing, the engineers from the digital team are reluctant to implement it because it's not standard. Please read: https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth What do you guys think?

**Comment by joshblack** [comment]
We do have the following properties turned on for smoothing currently:

```
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale
```

Which should correspond to the `font-smooth` stuff you all mentioned. It definitely makes a difference so would be down to do it by default. We can always have the properties behind a flag for teams that would like to configure it too, if needed 👍

**Comment by mjabbink** [comment]
What and who’s standard is always my question. Cameron and Peter have a good case to do it. Standard means nothing if there are no ramifications for those who have browsers that don’t support and those who do benefit. We should get Cameron to walk us through the findings.

**Comment by joshblack** [comment]
> Looks great. Do these tokens implement line height as well or is that applied elsewhere?

@wonilsuhibm it should implement all line heights, however for the fluid type we do %-based line-heights so that it grows as needed. Let me know if you want to check what I have set! I determined the % for each step by dividing the line-height by the font-size for each breakpoint and multiplied it by 100

**Comment by joshblack** [comment]
Sounds good, @mjabbink!

**Comment by mjabbink** [comment]
Sounds good @joshblack

**Comment by joshblack** [comment]
Just updated to pull in the italic set from Google Fonts for IBM Plex Sans. Hopefully netlify will comment with the updated preview link soon 👍 cc @aagonzales 

I manually verified that it downloaded but would be great to get another eye.

One thing I forgot to mention that might not be obvious is to disable local IBM Plex fonts when reviewing. The style inspector should have this hint at the bottom telling you where the glyphs come from:

screen shot 2018-12-05 at 6 23 41 pm

I ran into trouble removing it from my machine since it's considered a system-level font on our laptops, so I ended up just manually removing the folder it was in and then restoring it when I was done testing.

**Comment by photodow** [comment]
> Regarding font smoothing, the engineers from the digital team are reluctant to implement it because it's not standard.

@wonilsuhibm I wouldn't be so quick to dismiss it because of its lack of standards. They have some browser prefixes to help that along a little. We're currently using it across IBM.com on our icon font. I've wondered in the past why we're not including it for type too. I personally don't feel it would be a huge stretch to bring it into type if everyone agrees it improves it. My experience with it up to this point is it's pretty consistent across browsers, and it gracefully degrades if it isn't support.

@mjabbink with that said, I'd still love to see what Cameron, and Peter have to say.

> I ended up just manually removing the folder it was in and then restoring it when I was done testing.

@joshblack I spent 2 hours last week trying to figure this out to no avail, thanks so much! Having Plex as a system font is great, but not when you're trying to test it as if you were a user without Plex.

> I determined the % for each step by dividing the line-height by the font-size for each breakpoint and multiplied it by 100

@joshblack I'm hoping to take a closer look at how you're handling the fluid type tomorrow. My brain is having a hard time comprehending your function this late at night. I'm more genuinly curious about how it's working more than I see any issue with it at the moment. For the most part everything else looks good. I do have a question around why y'all are being so explicit/repetitive with some of the properties and values. Thinking about that translating to our needs on Digital I fear it might add some uncessary weight to the code base. I'll reach out to you seperately about this though.

Looking good :+1:

**Comment by wonilsuhibm** [comment]
Regarding the smoothing, I am actually for implementing it. I just wantd to get a bit wider perspective. As long as the three main browsers render this option, I'd say implement it until it gets deprecated or standardized.

**Comment by joshblack** [comment]
@photodow sounds good! Let me know if I can help out or if any additional notes would make approaching it easier. Most of the logic comes from: https://css-tricks.com/snippets/css/fluid-typography/

On a separate note, was surprised about the size comment as I had assumed it would be negligible. If looking into delivering CSS with gzip, I had assumed the difference in size would be on the order of bytes. We could definitely remove all the sans ones if it would help but would rather address that if the problem comes up then making changes prematurely.

**Comment by joshblack** [comment]
Hey all! 👋 Merging this in now, if you have any feedback feel free to leave it in on this PR or create an issue and we can address it. Thanks!

**Pull request merged**
