### PR TITLE
Add colors package

### PR DESCRIPTION
**Pull request by joshblack**
Adds in the color package with support for JavaScript and SCSS variables.

#### Changelog

**New**

- `packages/colors`

**Changed**

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @lovemecomputer

**Comment by joshblack** [comment]
I'm down to switch @alisonjoseph, also don't mind just having the exports be the colors themselves, e.g. `$magenta-100`

**Comment by aledavila** [comment]
How necessary is it to have IBM ? is it an open source thing to brand?

**Comment by alisonjoseph** [comment]
I'd be ok with just `$magenta-100` I think. Any downside to that?

**Comment by joshblack** [comment]
I think the idea was to use it to namespace the value so there was less chance of collision. I think we could totally do `magenta-100` and if this issue comes up we could offer prefixed-variables as well?

**Comment by joshblack** [comment]
Up for either 👍 Shorter the better for people using the colors, I guess, but then shorter the name the greater the chance of collision.

**Comment by aledavila** [comment]
Can we use a `c--` for carbon ?

**Comment by alisonjoseph** [comment]
I wouldn't use a C, since we don't even know if the Carbon name is sticking around 😞

**Comment by joshblack** [comment]
How about we stick with `ibm-colors` for this PR, just since it seems the least controversial of the options. Folks can also re-map the names to better ones in their project if they are using the values a ton 👍

**Comment by alisonjoseph** [comment]
sounds good 👍

**Comment by lovemecomputer** [comment]
yah agreed, something with `ibm-*` prefix specifically taxonomizes the color as being derived from the ibm color swatch list (as opposed to say, another magenta that someone made up)

**Pull request merged**
