### PR TITLE
feat(type): add type package

### LINKED ISSUE #13: Verify type scale and styles for `carbon-elements`
This issue is for design to sign-off on the existing type scales and styles for the IDL refresh that's making it's way into our OSS `carbon-elements` project.

The current set of styles for both projects are currently at:

- [IDL Refresh](https://duo.w3ibm.mybluemix.net/elements/type-specs/#type-set) (internal)
- [Carbon Design System](http://carbondesignsystem.com/style/typography/type-styles)

Some of the differences that we need to settle on or confirm:

- [ ] Type scale naming conventions
  - Do we use an alphabet scale, greek, phonetic, etc
  - Do we need custom steps for font families? Like Type A Mono
  - How should we differentiate "tight" options, like Type B and Type B Tight
- [ ] Type scale styles
  - Verify the specs match what needs to be in OSS
  - Verify that responsive specs match the needs that we have
  - Verify whether things like margin (top/bottom) should be specified on these type styles

### PR DESCRIPTION
**Pull request by joshblack**
Add in initial type package

#### Changelog

**New**

- Type
  - JS Support
  - SCSS Support
  - Example

**Changed**

**Removed**

#### Testing & Reviewing

Preview URLs

- [Type example](https://joshblack.github.io/carbon-elements/type/examples/basic/index.html)

### CODE REVIEW

**Comment by joshblack** [comment]
Yupp, agreed @asudoh!

**Comment by joshblack** [comment]
Note to designers reviewing, the fonts will load if you have them available locally. Unfortunately this example doesn't have the code needed to load the fonts specifically, this just brings in the styles. The page should render like:

screen shot 2018-09-20 at 1 40 06 pm

And the sections are the token categories, and they go from smallest to largest (heading-01 -> heading-06).

**Comment by seejamescode** [comment]
Quick question: Will this package include editorial and display sizes later on? Even when in product codebases, you will run across marketing areas like a before-login landing page.

**Comment by joshblack** [comment]
Yupp! Just need to add them in 😄 @seejamescode

**Comment by joshblack** [comment]
Removing the "close" labels and am going to merge this in. Will still need to make a PR that addresses those comments, in addition to the other tokens that @seejamescode mentioned!

**Pull request merged**
