### PR TITLE
warning--filled--layered.svg with stylable [!]

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
Closes #

adds a warning--filled--layered.svg with stylable [!] so the BG fill and [!] can be independantly styled via css.

#### Changelog

**New**

16/warning--filled--layered.svg
20/warning--filled--layered.svg
24/warning--filled--layered.svg
32/warning--filled--layered.svg

### CODE REVIEW

**Comment by chrisconnors-ibm** [comment]
@joshblack please confirm the two elements are independently stylable via CSS.

cc @shixiedesign @aagonzales

**Comment by aagonzales** [comment]
@chrisconnors-ibm is this a separate issue then what got added here: https://github.com/IBM/carbon-elements/pull/374 ?

**Comment by shixiedesign** [comment]
This is a different design, and not one we currently offer. If we want to add a new icon, we should remove the old one that's very similar: 
image

**Comment by chrisconnors-ibm** [comment]
build is ignoring the `white` [!] shape layer:
image

**Comment by joshblack** [comment]
@chrisconnors-ibm we can target the `!` path to flip it to white 👍 By default it's black so it looks filled in

**Comment by chrisconnors-ibm** [comment]
it will be hard to troubleshoot if we render it unstyled as just a single mass of black.

**Comment by joshblack** [comment]
@chrisconnors-ibm agreed, that's why I was asking about that `fill-rule` thing or other CSS things to help fix this. Is there anyone with some expertise here that we could bug to see if we can do anything?

**Comment by aagonzales** [comment]
I think its supposed to be black because the icons will be changed to yellow and the ! will need to be black for accessibility.

**Comment by chrisconnors-ibm** [comment]
we shouldn't be throwing away the `white` fill on the [!] when the icon colors are _not_ being overridden via css styling.

**Comment by chrisconnors-ibm** [comment]
> This is a different design, and not one we currently offer. If we want to add a new icon, we should remove the old one that's very similar:
 
it's meant to replace `16/warning--filled.svg` but until @joshblack can confirm/demonstrate that we can independently style the circle bg color and the [!] color.

When it's unstyled, as in the ESM demo site of in our icon library, they should remain circle bc color `black` and [!] color `white`

The other difference between this and #374 is that it includes all 4 sizes, and the [!] is based on Plex Sans (as it was in @conradennis' original)

**Comment by chrisconnors-ibm** [comment]
I have a new set of guidance/assets from @conradennis that I'll up this afternoon.

**Comment by joshblack** [comment]
Yup, we can style it. Although the default will still be the filled in black unless we find a way to avoid that 🤔

**Pull request merged**
